name = "crm-cms-api"
main = "index.js"
compatibility_date = "2026-05-03"

kv_namespaces = [
  { binding = "KV", id = "080dd2790ce948f8bea2a77c48f13fa6" }
]

[vars]
STRIPE_PUBLISHABLE_KEY = ""
ADMIN_API_KEY = "crm-cms-admin-secret-key-change-me"

routes = [
  { pattern = "crm-cms-store.pages.dev/api/*", zone_id = "" }
]
